name: Run fal scripts

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8.x"]
        dbt: ["0.20.1", "0.21.1"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt
          pip install dbt==${{ matrix.dbt }}

      - name: Setup secret key
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > $HOME/keyfile.json
          ls -la $HOME/keyfile.json
          echo 'keyfile is ready'

      - name: Run dbt and fal
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          export KEYFILE_DIR=$HOME
          dbt seed --profiles-dir .
          dbt run --profiles-dir . --full-refresh
          fal run --profiles-dir .
