name: Run fal scripts

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Setup dbt profile
        run: |
          mkdir $HOME/.dbt
          cp profiles.yml $HOME/.dbt/
          ls -la $HOME/.dbt/
          echo 'dbt profile is ready'

      - name: Setup secret key
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > $HOME/keyfile.json
          ls -la $HOME/keyfile.json
          echo 'keyfile is fine'
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Run dbt and fal
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        run: |
          export KEYFILE_DIR=$HOME
          dbt run
          fal run
