name: Run fal scripts

on:
  push:
    branches: [ test_release ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          dbt run
          fal run
