version: 2

sources:
  - name: results
    database: "{{ env_var('GCLOUD_PROJECT') }}"
    schema: "{{ env_var('BQ_DATASET') }}"
    tables:
      - name: ticket_data_sentiment_analysis

models:
  - name: boston
    description: Ozone levels
    config:
      materialized: table
    meta:
      owner: "@meder"
      fal:
        scripts:
          - fal_scripts/slack.py
          - fal_scripts/send_datadog_event.py
  - name: stg_zendesk_ticket_data
    description: zendesk ticket data
    config:
      materialized: table
    meta:
      owner: "@meder"
      fal:
        scripts:
          - fal_scripts/slack.py
          - fal_scripts/write_to_firestore.py
          - fal_scripts/zendesk_sentiment_analysis.py
  - name: zendesk_ticket_metrics
    description: Zendesk ticket metrics
    config:
      materialized: table
    meta:
      owner: "@gorkem"
      fal:
        scripts:
          - fal_scripts/forecast_slack.py
  - name: lombardia_covid
    description: Lombardia (IT) Covid19 Cases
    config:
      materialized: table
    meta:
      owner: "@omer"
      fal:
        scripts:
          - fal_scripts/anomaly_detection.py

fal:
  scripts:
    - fal_scripts/upload_to_gcs.py
    - fal_scripts/upload_to_s3.py
    - fal_scripts/list_owners_of_models.py
