version: 2

models:
  - name: boston
    description: Ozone levels
    config:
      materialized: table
    columns:
      - name: y
        description: Ozone level
      - name: ds
        description: Date
    meta:
      fal:
        scripts: ["fal_scripts/slack.py"]
